### ISSUE TITLE
ranger plugin crashes with listrdbc() gaian function used

### ISSUE THREAD

**Issue by planetf1** [GaianRangerPlugin/ranger-gaian-plugin#3]
* Configured gaian with latest policy plugin
* Table functions in use
* Have a datasource configured. Access control policy is permit all. 2 masking policies on very specific columns
* Using gaan dashboard (launchDashboard.sh) tried the function 'call listrdbc()' to list existing jdbc connections (this will be used by the VDC Virtualiser component)
* Gaian immediately crashes with an exception

Derby Version: CSS10081/10.8.3.1 - (1505077)  - Java Version: 1.8.0_151 (OpenJDK 64-Bit Server VM)

GaianNode started for Derby network server with sslMode=off on port: 6414 at Tue Mar 13 18:26:53 WET 2018, startup time: 1178ms

Loading policy class: org.apache.ranger.services.gaian.RangerPolicyResultFilter
log4j:WARN No appenders could be found for logger (org.apache.ranger.services.gaian.RangerGaianAuthorizer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "GaianDataSourceExecutor-1" java.lang.ArrayIndexOutOfBoundsException: 13
	at org.apache.ranger.services.gaian.RangerPolicyResultFilter.filterRowsBatch(RangerPolicyResultFilter.java:201)
	at com.ibm.gaiandb.GaianResult.run(GaianResult.java:714)
	at com.ibm.gaiandb.GaianSubResult.run(GaianSubResult.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by planetf1** [comment]
Note this is in my code hack to address format differences ...

**Comment by planetf1** [comment]
This is now resolved
